### PR TITLE
Add StorageType.AppDomainData-2

### PR DESCRIPTION
**Pull request by dotnetchris**
Allow ASP.NET apps to easily write to the ~\App_Data\ location. The
default "Local" location is wiped upon IIS recycling unless
nonstandard-configuration of LoadUserProfile is added. Also add some
documentation to enum members

### CODE REVIEW

**Comment by dotnetchris** [comment]
Please ping this when you update the nuget package so i can remove my custom build and use the package again.

**Comment by furier** [comment]
Will do! :)

tir. 26. jan. 2016 kl. 23.56 skrev Chris Marisic notifications@github.com:

**Comment by furier** [comment]
done!

**Comment by dotnetchris** [comment]
@furier switched back to the package, looks good. thanks!

**Comment by furier** [comment]
:+1:

**Pull request merged**
