### PR TITLE
Add StorageType.AppDomainData

### PR DESCRIPTION
**Pull request by dotnetchris**
Allow ASP.NET apps to easily write to the ~\App_Data\ location. The default "Local" location is wiped upon IIS recycling unless nonstandard-configuration of LoadUserProfile is added. Also add some documentation to enum members.

Other hosting environments can utilize the "DataDirectory" folder with differing folder locations http://stackoverflow.com/a/12268705/37055 also allows custom manipulation given a usage of the SetData method.

### CODE REVIEW

**Comment by furier** [comment]
Looks good after some research, but I would have to ask you to fix the
commits. I don't see the reason for the first one.
lør. 9. jan. 2016 kl. 01.01 skrev Chris Marisic <notifications@github.com>:

**Comment by dotnetchris** [comment]
The first commit is just a pull & merge from remote as opposed to rebase. If it's really that important i can delete my fork, new fork, copy / paste changes.

**Comment by dotnetchris** [comment]
Thoughts?

**Comment by furier** [comment]
My silence kinda implied that, but if you dont mind that would be nice and ill merge it and deploy it.

PS: Cant you use the merge commits feature?

**Pull request closed without merging**
